### ISSUE TITLE
Usage Confusion

### ISSUE THREAD

**Issue by RobTables** [lencioni/consolidated-events#17]
I am attempting to replace some code that makes use of this library to instead use `EventTarget.addEventListener()`. I am a bit confused with some of the naming done which uses the same convention as the example.

When I see `addEventListener` assigned to `removeEventListener` in the example 

```
const removeEventListener = addEventListener(
  window,
  'scroll',
  () => { console.log('scrolling') },
  { passive: true }
);
```

The name of the function would leave one to assume it mimics `EventTarget.removeEventListener()` when called

```
removeEventListener();
```

Could someone clear this up for me?

**Comment by lencioni** [comment]
addEventListener here returns a function that when called will remove the event listener that was added. Does that help?

**Comment by RobTables** [comment]
@lencioni yes that definitely clears that up, thank you
