### ISSUE TITLE
Removing events during a handleEvent iteration can cause handlers to be skipped

### ISSUE THREAD

**Issue by aaronholsonege** [lencioni/consolidated-events#5]
Removing an event handler during an active handleEvent iteration can causes other handlers to be skipped:

```javascript
const removeClickListener = addEventListener(document, 'click', handler);
const removeAnotherClickListener = addEventListener(document, 'click', anotherHandler);

function handler() {
  removeClickListener(); // remove myself
}

function anotherHandler() {
  // I am never called!
}
```

This could be solved [here](https://github.com/lencioni/consolidated-events/blob/master/src/TargetEventHandlers.js#L24) by making a copy of the handler array before iterating through it, so any removed handlers will not affect the current iteration.

```javascript
handlers.slice().forEach((handler) => {
  ...
})
```

**Comment by ljharb** [comment]
.forEach isn't affected by mutating the array; a PR with a test case would be really helpful.

**Comment by aaronholsonege** [comment]
Created a PR with a failing test case.

**Comment by aaronholsonege** [comment]
Found this on [MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/forEach#If_the_array_is_modified_during_iteration_other_elements_might_be_skipped.).

**Comment by ljharb** [comment]
mdn has a lot of sketchy polyfills, fwiw
